### ISSUE TITLE
Switch token, etc. to environment variables so we can have the config.ini file on the repo

### ISSUE THREAD

**Issue by kdspa** [atlacord/modmailbot#7]

**Comment by CaptainM777** [comment]
Hawky actually already uses environment variables for the bot token, the config file just needs to be unignored by git and committed.

**Comment by kdspa** [comment]
Oh sweet, I didn't see that

**Comment by CaptainM777** [comment]
I'll go ahead and make a PR for it if you're not going to do so.

**Comment by kdspa** [comment]
Feel free
